apiVersion: v1
kind: Service
metadata:
  name: azimsaiyed-website-service
spec:
  selector:
    app: azimsaiyed-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP